### PR TITLE
feat: add support for node 22

### LINKED ISSUE #87: Node 22 support
would it be possible to update https://github.com/tidev/node-ios-device/pull/84 for Node 22?

### PR DESCRIPTION
**Pull request by ewanharris**
node-pre-gyp is still dead so update the patch we use to build and nan to bring in Node 22 compatibility, still outputs some deprecations but builds just fine. Tested locally and `.devices` works as expected and is able to load the binding, have not tested anything further as I don't have the ability to

Closes #87

### CODE REVIEW

**Comment by ewanharris** [comment]
It looks like the issue is because of the python version which node-gyp fixed (nodejs/node-gyp/issues/2869), we need [npm 10.2.2](https://github.com/npm/cli/blob/latest/CHANGELOG.md#dependencies-14) or newer which 🤞🏻 should be in Node 18, if not I'll just add installing a new npm version

**Comment by ewanharris** [comment]
@cb1kenobi done and looks too be good!

**Review by cb1kenobi — APPROVED** [review]
Looks good!

**Comment by cb1kenobi** [comment]
node-ios-device@1.12.0 published

**Pull request merged**
